apiVersion: v1
kind: PersistentVolume
metadata:
  # must be unique for the entire cluster
  name: odata-nfs-gcepd
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: odata-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odata-nfs-gcepd
spec:
  storageClassName: ""
  volumeName: odata-nfs-gcepd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
