{{ if and .Values.enabled .Values.datastore.enabled .Values.db.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: datastore-db
spec:
  selector:
    app: datastore-db
  ports:
  - name: "5432"
    port: 5432
{{ end }}