{{ if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: solr
    spec:
      {{ if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector }}
      {{ end }}
      initContainers:
      {{ if .Values.solrInitialize }}
      - name: initialize
        image: {{ .Values.alpineImage | quote }}
        command:
        - sh
        - "-c"
        - |
          rm -rf /opt/solr/server/solr/ckan/data/*
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /opt/solr/server/solr/ckan/data
          subPath: solr
      {{ end }}
      - name: permissions
        image: {{ .Values.alpineImage | quote }}
        command:
        - sh
        - "-c"
        - |
          chown -R 8983:8983 /opt/solr/server/solr/ckan/data &&\
          ls -lah /opt/solr/server/solr/ckan/data
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /opt/solr/server/solr/ckan/data
          subPath: solr
      containers:
      - image: {{ .Values.solrImage | quote }}
        name: solr
        ports:
        - containerPort: 8983
        resources: {{ .Values.solrResources }}
        volumeMounts:
        - name: data
          mountPath: /opt/solr/server/solr/ckan/data
          subPath: solr
      volumes:
      - name: data
        {{ if .Values.hostPath }}
        hostPath:
          path: {{ .Values.hostPath | quote }}
          type: DirectoryOrCreate
        {{ else }}
        nfs:
          server: {{ .Values.ckanDataNfsServer | default "nfs" | quote }}
          path: "/"
        {{ end }}
{{ end }}
